import type { StrategyId, StrategyMeta } from "./types";

export const STRATEGIES: Record<StrategyId, StrategyMeta> = {
  opening_range_breakout: {
    id: "opening_range_breakout",
    label: "Opening Range Breakout",
    family: "breakout",
    description: "Take the first decisive break of the opening range in the dominant direction.",
    entryDescription: "Enter on close beyond ORH/ORL with volume confirmation.",
    invalidation: "Reclaim back inside opening range.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 2.0,
    edge: { winRate: 0.44, avgWinR: 2.0, avgLossR: 1.0, tradesPerDay: 2 },
    quality: {
      primaryTrigger: "breakout_close",
      vwap: { preference: "above", slopeMatters: true },
      profile: { preferredLocations: ["value_edge", "range_edge", "lvn"], requiresLocation: false },
      footprint: { preferredSignals: ["imbalance_with", "absorption"] },
      stopType: "or_invalidation",
      firstStructureTargets: ["vah", "val", "poc", "hvn"],
      abortConditions: ["reclaim_back_inside_or_within_2_bars", "volume_dies_immediately_post_break"],
    },
  },
  expansion_breakout: {
    id: "expansion_breakout",
    label: "Expansion Breakout",
    family: "breakout",
    description: "Enter on volatility expansion outside prior value with accepting tape.",
    entryDescription: "Enter on breakout candle close with range > 1.4 × ATR.",
    invalidation: "Price re-enters prior value area within one bar.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.2,
    edge: { winRate: 0.42, avgWinR: 2.2, avgLossR: 1.0, tradesPerDay: 1 },
    quality: {
      primaryTrigger: "breakout_close",
      vwap: { preference: "above", slopeMatters: true },
      profile: { preferredLocations: ["value_edge", "lvn"], requiresLocation: false },
      footprint: { preferredSignals: ["imbalance_with", "absorption"] },
      stopType: "or_invalidation",
      firstStructureTargets: ["vah", "val", "hvn"],
      abortConditions: ["re_entry_into_value_within_1_bar", "expansion_range_lt_1x_atr"],
    },
  },
  breakout_continuation: {
    id: "breakout_continuation",
    label: "Breakout Continuation",
    family: "breakout",
    description: "Join a confirmed breakout on the first shallow retest.",
    entryDescription: "Enter on pullback holding prior breakout level.",
    invalidation: "Close back through breakout pivot.",
    defaultStopAtrMult: 0.8,
    defaultTargetR: 1.8,
    edge: { winRate: 0.48, avgWinR: 1.8, avgLossR: 1.0, tradesPerDay: 2 },
    quality: {
      primaryTrigger: "retest_hold",
      vwap: { preference: "above", slopeMatters: true },
      profile: { preferredLocations: ["value_edge", "lvn", "range_edge"], requiresLocation: false },
      footprint: { preferredSignals: ["absorption", "imbalance_with"] },
      stopType: "retest_fail",
      firstStructureTargets: ["vah", "val", "poc"],
      abortConditions: ["reaccept_inside_prior_range", "pullback_deep_past_0.5_retest"],
    },
  },
  trend_pullback_continuation: {
    id: "trend_pullback_continuation",
    label: "Trend Pullback Continuation",
    family: "trend",
    description: "Buy-the-dip / sell-the-rip in a qualified trending regime.",
    entryDescription: "Enter on pullback to VWAP or 20EMA with momentum trigger.",
    invalidation: "Lose VWAP / prior swing pivot.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.0,
    edge: { winRate: 0.50, avgWinR: 2.0, avgLossR: 1.0, tradesPerDay: 2 },
    quality: {
      primaryTrigger: "retest_hold",
      vwap: { preference: "above", slopeMatters: true },
      profile: { preferredLocations: ["value_edge", "hvn", "poc"], requiresLocation: false },
      footprint: { preferredSignals: ["absorption", "imbalance_with"] },
      stopType: "vwap_break",
      firstStructureTargets: ["vah", "val", "hvn"],
      abortConditions: ["vwap_lost_decisively", "pullback_becomes_structure_break"],
    },
  },
  balanced_auction_rotation: {
    id: "balanced_auction_rotation",
    label: "Balanced Auction Rotation",
    family: "range",
    description: "Rotate between value-area extremes inside balance.",
    entryDescription: "Fade VAH / VAL with rotational confirmation.",
    invalidation: "Breakout acceptance outside value area.",
    defaultStopAtrMult: 0.7,
    defaultTargetR: 1.5,
    edge: { winRate: 0.58, avgWinR: 1.5, avgLossR: 1.0, tradesPerDay: 3 },
    quality: {
      primaryTrigger: "rejection",
      vwap: { preference: "flat", slopeMatters: false },
      profile: { preferredLocations: ["vah", "val", "value_edge", "failed_auction_edge"], requiresLocation: true },
      footprint: { preferredSignals: ["exhaustion", "absorption"] },
      stopType: "range_opposite_edge",
      firstStructureTargets: ["poc", "vah", "val"],
      abortConditions: ["accept_outside_value_area", "trend_day_detected"],
    },
  },
  balanced_range: {
    id: "balanced_range",
    label: "Balanced Range",
    family: "range",
    description: "Mechanical range-high / range-low scalps with tight risk.",
    entryDescription: "Fade range extremes on failure to expand.",
    invalidation: "Close outside range mid.",
    defaultStopAtrMult: 0.6,
    defaultTargetR: 1.3,
    edge: { winRate: 0.60, avgWinR: 1.3, avgLossR: 1.0, tradesPerDay: 3 },
    quality: {
      primaryTrigger: "rejection",
      vwap: { preference: "flat", slopeMatters: false },
      profile: { preferredLocations: ["range_edge", "vah", "val"], requiresLocation: true },
      footprint: { preferredSignals: ["exhaustion"] },
      stopType: "range_opposite_edge",
      firstStructureTargets: ["poc", "vah", "val"],
      abortConditions: ["close_outside_range_mid", "range_expansion_starts"],
    },
  },
  vwap_reclaim_mean_reversion: {
    id: "vwap_reclaim_mean_reversion",
    label: "VWAP Reclaim / Mean Reversion",
    family: "reversal",
    description: "Reclaim of VWAP after probe; fade stretched move back to mean.",
    entryDescription: "Enter on VWAP reclaim candle with momentum shift.",
    invalidation: "Rejection back through VWAP.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 1.8,
    edge: { winRate: 0.52, avgWinR: 1.8, avgLossR: 1.0, tradesPerDay: 2 },
    quality: {
      primaryTrigger: "reclaim",
      vwap: { preference: "reclaim_above", slopeMatters: false },
      profile: { preferredLocations: ["poc", "vah", "val"], requiresLocation: true },
      footprint: { preferredSignals: ["absorption", "delta_divergence"] },
      stopType: "vwap_break",
      firstStructureTargets: ["poc", "vah", "val"],
      abortConditions: ["vwap_rejects_reclaim_within_2_bars", "no_prior_extension_to_fade"],
    },
  },
  counter_trend_fade_failed_breakout: {
    id: "counter_trend_fade_failed_breakout",
    label: "Counter-Trend Fade / Failed Breakout",
    family: "reversal",
    description: "Fade a failed break that fails to hold beyond the pivot.",
    entryDescription: "Enter on reclaim candle after failed breakout.",
    invalidation: "New high / low beyond failed pivot.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 2.0,
    edge: { winRate: 0.46, avgWinR: 2.0, avgLossR: 1.0, tradesPerDay: 1 },
    quality: {
      primaryTrigger: "reclaim",
      vwap: { preference: "reclaim_below", slopeMatters: false },
      profile: { preferredLocations: ["value_edge", "failed_auction_edge"], requiresLocation: true },
      footprint: { preferredSignals: ["exhaustion", "absorption", "delta_divergence"] },
      stopType: "sweep_extreme",
      firstStructureTargets: ["vah", "val", "poc"],
      abortConditions: ["new_extreme_beyond_pivot", "acceptance_outside_value_resumes"],
    },
  },
  liquidity_sweep_and_reclaim: {
    id: "liquidity_sweep_and_reclaim",
    label: "Liquidity Sweep & Reclaim",
    family: "reversal",
    description: "Sweep of obvious liquidity level followed by immediate reclaim.",
    entryDescription: "Enter on reclaim bar after sweep of prior H/L.",
    invalidation: "Failure to reclaim within 2 bars.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.0,
    edge: { winRate: 0.50, avgWinR: 2.0, avgLossR: 1.0, tradesPerDay: 1 },
    quality: {
      primaryTrigger: "sweep_reclaim",
      vwap: { preference: "any", slopeMatters: false },
      profile: { preferredLocations: ["value_edge", "failed_auction_edge", "lvn"], requiresLocation: true },
      footprint: { preferredSignals: ["exhaustion", "delta_divergence"] },
      stopType: "sweep_extreme",
      firstStructureTargets: ["poc", "vah", "val"],
      abortConditions: ["fails_to_reclaim_in_2_bars", "accepts_beyond_sweep_extreme"],
    },
  },
  reversal_mean_reversion: {
    id: "reversal_mean_reversion",
    label: "Reversal Mean Reversion",
    family: "reversal",
    description: "Full reversal setup with structure break in opposite direction.",
    entryDescription: "Enter on lower-high / higher-low structure confirmation.",
    invalidation: "New extreme beyond reversal pivot.",
    defaultStopAtrMult: 1.1,
    defaultTargetR: 2.2,
    edge: { winRate: 0.44, avgWinR: 2.2, avgLossR: 1.0, tradesPerDay: 1 },
    quality: {
      primaryTrigger: "structure_break",
      vwap: { preference: "reclaim_below", slopeMatters: true },
      profile: { preferredLocations: ["value_edge", "failed_auction_edge"], requiresLocation: true },
      footprint: { preferredSignals: ["delta_divergence", "exhaustion"] },
      stopType: "swing_structure",
      firstStructureTargets: ["vah", "poc", "val"],
      abortConditions: ["new_extreme_confirms_continuation", "no_structure_break_yet"],
    },
  },
  low_quality_no_trade: {
    id: "low_quality_no_trade",
    label: "Low Quality / No Trade",
    family: "passive",
    description: "Edge insufficient — reduced-size only if minimally acceptable.",
    entryDescription: "Stand aside unless probe-level edge is clear.",
    invalidation: "N/A",
    defaultStopAtrMult: 0.8,
    defaultTargetR: 1.2,
    edge: { winRate: 0.35, avgWinR: 1.2, avgLossR: 1.0, tradesPerDay: 1 },
  },
  event_driven_high_risk: {
    id: "event_driven_high_risk",
    label: "Event Driven / High Risk",
    family: "passive",
    description: "Scheduled event window — stand aside unless event-trading mode is on.",
    entryDescription: "No entry.",
    invalidation: "N/A",
    defaultStopAtrMult: 0,
    defaultTargetR: 0,
    edge: { winRate: 0, avgWinR: 0, avgLossR: 1.0, tradesPerDay: 0 },
  },
};

export const STRATEGY_LIST: StrategyMeta[] = Object.values(STRATEGIES);

// Expectancy in R per trade from the playbook's edge preset.
// Positive = net winning edge, negative = net losing edge.
export function strategyExpectancy(id: StrategyId): number {
  const e = STRATEGIES[id].edge;
  return e.winRate * e.avgWinR - (1 - e.winRate) * e.avgLossR;
}

// Normalize per-strategy expectancy to a 0..1 edge score the decision
// engine can blend with its other factors. Maps the realistic
// expectancy range [-0.5R .. +1.0R] onto [0 .. 1]; anything outside
// clamps to the ends.
export function strategyEdgeScore(id: StrategyId): number {
  const exp = strategyExpectancy(id);
  return Math.max(0, Math.min(1, (exp + 0.5) / 1.5));
}
