import type { StrategyId, StrategyMeta } from "./types";

export const STRATEGIES: Record<StrategyId, StrategyMeta> = {
  opening_range_breakout: {
    id: "opening_range_breakout",
    label: "Opening Range Breakout",
    family: "breakout",
    description: "Take the first decisive break of the opening range in the dominant direction.",
    entryDescription: "Enter on close beyond ORH/ORL with volume confirmation.",
    invalidation: "Reclaim back inside opening range.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 2.0,
  },
  expansion_breakout: {
    id: "expansion_breakout",
    label: "Expansion Breakout",
    family: "breakout",
    description: "Enter on volatility expansion outside prior value with accepting tape.",
    entryDescription: "Enter on breakout candle close with range > 1.4 × ATR.",
    invalidation: "Price re-enters prior value area within one bar.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.2,
  },
  breakout_continuation: {
    id: "breakout_continuation",
    label: "Breakout Continuation",
    family: "breakout",
    description: "Join a confirmed breakout on the first shallow retest.",
    entryDescription: "Enter on pullback holding prior breakout level.",
    invalidation: "Close back through breakout pivot.",
    defaultStopAtrMult: 0.8,
    defaultTargetR: 1.8,
  },
  trend_pullback_continuation: {
    id: "trend_pullback_continuation",
    label: "Trend Pullback Continuation",
    family: "trend",
    description: "Buy-the-dip / sell-the-rip in a qualified trending regime.",
    entryDescription: "Enter on pullback to VWAP or 20EMA with momentum trigger.",
    invalidation: "Lose VWAP / prior swing pivot.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.0,
  },
  balanced_auction_rotation: {
    id: "balanced_auction_rotation",
    label: "Balanced Auction Rotation",
    family: "range",
    description: "Rotate between value-area extremes inside balance.",
    entryDescription: "Fade VAH / VAL with rotational confirmation.",
    invalidation: "Breakout acceptance outside value area.",
    defaultStopAtrMult: 0.7,
    defaultTargetR: 1.5,
  },
  balanced_range: {
    id: "balanced_range",
    label: "Balanced Range",
    family: "range",
    description: "Mechanical range-high / range-low scalps with tight risk.",
    entryDescription: "Fade range extremes on failure to expand.",
    invalidation: "Close outside range mid.",
    defaultStopAtrMult: 0.6,
    defaultTargetR: 1.3,
  },
  vwap_reclaim_mean_reversion: {
    id: "vwap_reclaim_mean_reversion",
    label: "VWAP Reclaim / Mean Reversion",
    family: "reversal",
    description: "Reclaim of VWAP after probe; fade stretched move back to mean.",
    entryDescription: "Enter on VWAP reclaim candle with momentum shift.",
    invalidation: "Rejection back through VWAP.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 1.8,
  },
  counter_trend_fade_failed_breakout: {
    id: "counter_trend_fade_failed_breakout",
    label: "Counter-Trend Fade / Failed Breakout",
    family: "reversal",
    description: "Fade a failed break that fails to hold beyond the pivot.",
    entryDescription: "Enter on reclaim candle after failed breakout.",
    invalidation: "New high / low beyond failed pivot.",
    defaultStopAtrMult: 0.9,
    defaultTargetR: 2.0,
  },
  liquidity_sweep_and_reclaim: {
    id: "liquidity_sweep_and_reclaim",
    label: "Liquidity Sweep & Reclaim",
    family: "reversal",
    description: "Sweep of obvious liquidity level followed by immediate reclaim.",
    entryDescription: "Enter on reclaim bar after sweep of prior H/L.",
    invalidation: "Failure to reclaim within 2 bars.",
    defaultStopAtrMult: 1.0,
    defaultTargetR: 2.0,
  },
  reversal_mean_reversion: {
    id: "reversal_mean_reversion",
    label: "Reversal Mean Reversion",
    family: "reversal",
    description: "Full reversal setup with structure break in opposite direction.",
    entryDescription: "Enter on lower-high / higher-low structure confirmation.",
    invalidation: "New extreme beyond reversal pivot.",
    defaultStopAtrMult: 1.1,
    defaultTargetR: 2.2,
  },
  low_quality_no_trade: {
    id: "low_quality_no_trade",
    label: "Low Quality / No Trade",
    family: "passive",
    description: "Edge insufficient — reduced-size only if minimally acceptable.",
    entryDescription: "Stand aside unless probe-level edge is clear.",
    invalidation: "N/A",
    defaultStopAtrMult: 0.8,
    defaultTargetR: 1.2,
  },
  event_driven_high_risk: {
    id: "event_driven_high_risk",
    label: "Event Driven / High Risk",
    family: "passive",
    description: "Scheduled event window — stand aside unless event-trading mode is on.",
    entryDescription: "No entry.",
    invalidation: "N/A",
    defaultStopAtrMult: 0,
    defaultTargetR: 0,
  },
};

export const STRATEGY_LIST: StrategyMeta[] = Object.values(STRATEGIES);
